# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: Provides an essential, core set of commands for Bukkit.
softdepend: [Vault, LuckPerms]
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, mdcfe, JRoy, pop4959]
api-version: "1.13"
commands:
  afk:
    description: Marks you as away-from-keyboard.
    usage: /<command> [player/message...]
    aliases: [eafk,away,eaway]
  anvil:
    description: Opens up an Anvil.
    usage: /<command>
    aliases: [eanvil]
  back:
    description: Teleports you to your location prior to tp/spawn/warp.
    usage: /<command> [player]
    aliases: [eback,return,ereturn]
  balance:
    description: States the current balance of a player.
    usage: /<command> [player]
    aliases: [bal,ebal,ebalance,money,emoney]
  balancetop:
    description: Gets the top balance values.
    usage: /<command> [page]
    aliases: [ebalancetop,baltop,ebaltop]
  broadcast:
    description: Broadcasts a message to the entire server.
    usage: /<command> <msg>
    aliases: [bc,ebc,bcast,ebcast,ebroadcast,shout,eshout]
  clearinventory:
    description: Clear all items in your inventory.
    usage: /<command> [player|*] [item[:<data>]|*|**] [amount]
    aliases: [ci,eci,clean,eclean,clear,eclear,clearinvent,eclearinvent,eclearinventory]
  clearinventoryconfirmtoggle:
    description: Toggles whether you are prompted to confirm inventory clears.
    usage: /<command>
    aliases: [eclearinventoryconfirmtoggle, clearinventoryconfirmoff, eclearinventoryconfirmoff, clearconfirmoff, eclearconfirmoff, clearconfirmon, eclearconfirmon, clearconfirm, eclearconfirm]
  createkit:
    description: Create a kit in game!
    usage: /<command> <kitname> <delay>
    aliases: [kitcreate,createk,kc,ck]
  delkit:
    description: Deletes the specified kit.
    usage: /<command> <kit>
    aliases: [edelkit,remkit,eremkit,rmkit,ermkit,deletekit,edeletekit]
  eco:
    description: Manages the server economy.
    usage: /<command> <give|take|set|reset> <player> <amount>
    aliases: [eeco,economy,eeconomy]
  enchant:
    description: Enchants the item the user is holding.
    usage: /<command> <enchantmentname> [level]
    aliases: [eenchant,enchantment,eenchantment]
  enderchest:
    description: Lets you see inside an enderchest.
    usage: /<command> [player]
    aliases: [echest,eechest,eenderchest,endersee,eendersee,ec,eec]
  essentials:
    description: Reloads essentials.
    usage: /<command>
    aliases: [eessentials, ess, eess, essversion]
  exp:
    description: Give, set, reset, or look at a players experience.
    usage: /<command> [reset|show|set|give] [playername [amount]]
    aliases: [eexp,xp]
  feed:
    description: Satisfy the hunger.
    usage: /<command> [player]
    aliases: [eat,eeat,efeed]
  fly:
    description: Take off, and soar!
    usage: /<command> [player] [on|off]
    aliases: [efly]
  gamemode:
    description: Change player gamemode.
    usage: /<command> <survival|creative|adventure|spectator> [player]
    aliases: [adventure,eadventure,adventuremode,eadventuremode,creative,ecreative,eecreative,creativemode,ecreativemode,egamemode,gm,egm,gma,egma,gmc,egmc,gms,egms,gmt,egmt,survival,esurvival,survivalmode,esurvivalmode,gmsp,sp,egmsp,spec,spectator]
  gc:
    description: Reports memory, uptime and tick info.
    usage: /<command>
    aliases: [lag,elag,egc,mem,emem,memory,ememory,uptime,euptime,tps,etps,entities,eentities]
  give:
    description: Give a player an item.
    usage: /<command> <player> <item|numeric> [amount [itemmeta...]]
    aliases: [egive]
  god:
    description: Enables your godly powers.
    usage: /<command> [player] [on|off]
    aliases: [egod,godmode,egodmode,tgm,etgm]
  hat:
    description: Get some cool new headgear.
    usage: /<command> [remove]
    aliases: [ehat,head,ehead]
  heal:
    description: Heals you or the given player.
    usage: /<command> [player]
    aliases: [eheal]
  help:
    description: Views a list of available commands.
    usage: /<command> [search term] [page]
    aliases: [ehelp]
  info:
    description: Shows information set by the server owner.
    usage: /<command> [chapter] [page]
    aliases: [about,eabout,ifo,eifo,einfo,inform,einform,news,enews]
  invsee:
    description: See the inventory of other players.
    usage: /<command> <player>
    aliases: [einvsee]
  item:
    description: Spawn an item.
    usage: /<command> <item|numeric> [amount [itemmeta...]]
    aliases: [i,eitem,ei]
  itemdb:
    description: Searches for an item.
    usage: /<command> <item>
    aliases: [dura,edura,durability,edurability,eitemdb,itemno,eitemno]
  itemlore:
    description: Edit the lore of an item.
    usage: /<command> <add/set/clear> [text/line] [text]
    aliases: [lore, elore, ilore, eilore, eitemlore]
  itemname:
    description: Names an item.
    usage: /<command> [name]
    aliases: [iname, einame, eitemname, itemrename, irename, eitemrename, eirename]
  jump:
    description: Jumps to the nearest block in the line of sight.
    usage: /<command>
    aliases: [j,ej,ejump,jumpto,ejumpto]
  kill:
    description: Kills specified player.
    usage: /<command> <player>
    aliases: [ekill]
  kit:
    description: Obtains the specified kit or views all available kits.
    usage: /<command> [kit] [player]
    aliases: [ekit,kits,ekits]
  kitreset:
    description: Resets the cooldown on the specified kit.
    usage: /<command> <kit> [player]
    aliases: [ekitreset, kitr, ekitr, resetkit, eresetkit]
  list:
    description: List all online players.
    usage: /<command> [group]
    aliases: [elist,online,eonline,playerlist,eplayerlist,plist,eplist,who,ewho]
  near:
    description: Lists the players near by or around a player.
    usage: /<command> [playername] [radius]
    aliases: [enear,nearby,enearby]
  nick:
    description: Change your nickname or that of another player.
    usage: /<command> [player] <nickname|off>
    aliases: [enick,nickname,enickname]
  tpoffline:
    description: Teleport to a player's last known logout location
    usage: /<command> <player>
    aliases: [otp, offlinetp, tpoff, tpoffline, etpoffline]
  pay:
    description: Pays another player from your balance.
    usage: /<command> <player> <amount>
    aliases: [epay]
  paytoggle:
    description: Toggles whether you are accepting payments.
    usage: /<command> [player]
    aliases: [epaytoggle, payoff, epayoff, payon, epayon]
  payconfirmtoggle:
    description: Toggles whether you are prompted to confirm payments.
    usage: /<command>
    aliases: [epayconfirmtoggle, payconfirmoff, epayconfirmoff, payconfirmon, epayconfirmon, payconfirm, epayconfirm]
  ptime:
    description: Adjust player's client time. Add @ prefix to fix.
    usage: /<command> [list|reset|day|night|dawn|17:30|4pm|4000ticks] [player|*]
    aliases: [playertime,eplayertime,eptime]
  pweather:
    description: Adjust a player's weather
    usage: /<command> [list|reset|storm|sun|clear] [player|*]
    aliases: [playerweather,eplayerweather,epweather]
  realname:
    description: Displays the username of a user based on nick.
    usage: /<command> <nickname>
    aliases: [erealname]
  recipe:
    description: Displays how to craft items.
    usage: /<command> <item> [number]
    aliases: [formula,eformula,method,emethod,erecipe,recipes,erecipes]
  remove:
    description: Removes entities in your world.
    usage: /<command> <all|tamed|named|drops|arrows|boats|minecarts|xp|paintings|itemframes|endercrystals|monsters|animals|ambient|mobs|[mobType]> [radius|world]
    aliases: [eremove,butcher,ebutcher,killall,ekillall,mobkill,emobkill]
  repair:
    description: Repairs the durability of one or all items.
    usage: /<command> [hand|all]
    aliases: [fix,efix,erepair]
  rules:
    description: Views the server rules.
    usage: /<command> [chapter] [page]
    aliases: [erules]
  seen:
    description: Shows the last logout time of a player.
    usage: /<command> <playername>
    aliases: [eseen, ealts, alts]
  sell:
    description: Sells the item currently in your hand.
    usage: /<command> <<itemname>|<id>|hand|inventory|blocks> [amount]
    aliases: [esell]
  settpr:
    description: Set the random teleport location and parameters.
    usage: /<command> [center|minrange|maxrange] [value]
    aliases: [esettpr, settprandom, esettprandom]
  setworth:
    description: Set the sell value of an item.
    usage: /<command> [itemname|id] <price>
    aliases: [esetworth]
  showkit:
    description: Show contents of a kit.
    usage: /<command> <kitname>
    aliases: [kitpreview,preview,kitshow]
  editsign:
    description: Edits a sign in the world.
    usage: /<command> <set/clear/copy/paste> [line number] [text]
    aliases: [sign, esign, eeditsign]
  skull:
    description: Set the owner of a player skull
    usage: /<command> [owner]
    aliases: [eskull, playerskull, eplayerskull, head, ehead]
  spawnmob:
    description: Spawns a mob.
    usage: /<command> <mob>[:data][,<mount>[:data]] [amount] [player]
    aliases: [mob,emob,spawnentity,espawnentity,espawnmob]
  speed:
    description: Change your speed limits.
    usage: /<command> [type] <speed> [player]
    aliases: [flyspeed,eflyspeed,fspeed,efspeed,espeed,walkspeed,ewalkspeed,wspeed,ewspeed]
  sudo:
    description: Make another user perform a command.
    usage: /<command> <player> <command [args]>
    aliases: [esudo]
  thunder:
    description: Enable/disable thunder.
    usage: /<command> <true/false> [duration]
    aliases: [ethunder]
  time:
    description: Display/Change the world time. Defaults to current world.
    usage: /<command> [set|add] [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
    aliases: [day,eday,night,enight,etime]
  tp:
    description: Teleport to a player.
    usage: /<command> <player> [otherplayer]
    aliases: [tele,etele,teleport,eteleport,etp,tp2p,etp2p]
  tpa:
    description: Request to teleport to the specified player.
    usage: /<command> <player>
    aliases: [call,ecall,etpa,tpask,etpask]
  tpaall:
    description: Requests all players online to teleport to you.
    usage: /<command> <player>
    aliases: [etpaall]
  tpaccept:
    description: Accepts teleport requests.
    usage: /<command> [player|*]
    aliases: [etpaccept,tpyes,etpyes]
  tpahere:
    description: Request that the specified player teleport to you.
    usage: /<command> <player>
    aliases: [etpahere]
  tpall:
    description: Teleport all online players to another player.
    usage: /<command> [player]
    aliases: [etpall]
  tpauto:
    description: Automatically accept teleportation requests.
    usage: /<command> [player]
    aliases: [etpauto]
  tpacancel:
    description: Cancel all outstanding teleport requests. Specify [player] to cancel requests with them.
    usage: /<command> [player]
    aliases: [etpacancel]
  tpdeny:
    description: Rejects teleport requests.
    usage: /<command> [player|*]
    aliases: [etpdeny,tpno,etpno]
  tphere:
    description: Teleport a player to you.
    usage: /<command> <player>
    aliases: [s,etphere]
  tpo:
    description: Teleport override for tptoggle.
    usage: /<command> <player> [otherplayer]
    aliases: [etpo]
  tpohere:
    description: Teleport here override for tptoggle.
    usage: /<command> <player>
    aliases: [etpohere]
  tppos:
    description: Teleport to coordinates.
    usage: /<command> <x> <y> <z> [yaw] [pitch] [world]
    aliases: [etppos]
  tpr:
    description: Teleport randomly.
    usage: /<command>
    aliases: [etpr, tprandom, etprandom]
  tptoggle:
    description: Blocks all forms of teleportation.
    usage: /<command> [player] [on|off]
    aliases: [etptoggle]
  weather:
    description: Sets the weather.
    usage: /<command> <storm/sun> [duration]
    aliases: [rain,erain,sky,esky,storm,estorm,sun,esun,eweather]
  whois:
    description: Determine the username behind a nickname.
    usage: /<command> <nickname>
    aliases: [ewhois]
  workbench:
    description: Opens up a workbench.
    usage: /<command>
    aliases: [craft,ecraft,wb,ewb,wbench,ewbench,eworkbench]
  worth:
    description: Calculates the worth of items in hand or as specified.
    usage: /<command> <<itemname>|<id>|hand|inventory|blocks> [-][amount]
    aliases: [eprice,price,eworth]

permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
    children:
      essentials.gamemode.*: true
  # These permissions can't be assigned from player-commands for compatibility reasons
  essentials.teleport.cooldown.bypass.tpa:
    default: true
    description: If the player does not have this permission, /tpa will have cooldown even with the parent bypass perm
  essentials.teleport.cooldown.bypass.back:
    default: true
    description: If the player does not have this permission, /back will have cooldown even with the parent bypass perm
  essentials.gamemode.*:
    default: op
    children:
      essentials.gamemode: true
      essentials.gamemode.others: true
      essentials.gamemode.all: true
  essentials.seen.extra:
    default: op
    children:
      essentials.seen.ip: true
      essentials.seen.location: true
      essentials.seen.uuid: true
      essentials.seen.whitelist: true
  essentials.keepinv:
    default: false
    description: Controls whether players keep their inventory on death.
  essentials.near.exclude:
    default: false
    description: If the player should be excluded from near lookups.
  essentials.keepxp:
    default: false
    description: Allows the user to keep their exp on death, instead of dropping it.
  essentials.invsee.preventmodify:
    default: false
    description: Prevents other players from modifying the players inventory.
  essentials.afk.auto:
    default: false
    description: Players with this permission will be set to afk after a period of inaction as defined in the config file.
  essentials.chat.ignoreexempt:
    default: false
    description: Someone with this permission will not be ignored, even if they are on another persons ignore list
  essentials.kit.exemptdelay:
    default: false
    description: Exempts you from the kit delay feature, this affects signs as well as command.
  essentials.silentjoin:
    default: false
    description: Allow to join silently
  essentials.silentquit:
    default: false
    description: Suppress leave/quit messages for users with this permission.
  essentials.sudo.exempt:
    default: false
    description: Prevents the holder from being sudo'ed by another user
  essentials.nick.allowunsafe:
    default: false
    description: If a player has this, they can set their username to any value. Use with caution, as this has the potential to break userdata files.
  essentials.balancetop.exclude:
    default: false
    description: Players with this permission are excluded from the balancetop
  essentials.back.onteleport:
    default: true
    description: Players with this permission will have back location stored during any teleportation
  essentials.back.ondeath:
    default: false
    description: Players with this permission will have back location stored during death
  essentials.exempt:
    default: false
    description: Parent permission to be exempt from many moderator actions
    children:
      essentials.chat.ignoreexempt: true
      essentials.sudo.exempt: true
      essentials.exempt.protect: true
      essentials.editsign.waxed.exempt: true
  essentials.nick.hideprefix:
    default: false
    description: Players with this permission will not have the nickname prefix applied to them
